-- LOT OF THINGS IN ID JEJE

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;

USE hbtn_0d_usa;

CREATE TABLE IF NOT EXISTS states (
    id int NOT NULL AUTO_INCREMENT UNIQUE,
    name varchar(256) NOT NULL,
    PRIMARY KEY (id)
);